# Hexo Theme configuration file

# User CSS (stylesheet)
css_files:
  - ## "/path/to/file" or URL

# Favicon file
favicon: favicon.png ## "path/to/file" or URL

# Global navigation
nav:
  - title: Home
    path: /
  - title: Archive
    path: /archives/

# Archive page / Archive widget
archive:
  date_format_for_monthly: YYYY年M月
  date_format_for_yearly: YYYY年

# Sidebar
sidebar:
  widgets:
    - intro
    - search
    - recent_posts
    - archive
    - tagcloud
    - tag
    - category
    - links
    - notice
  show_count:
    archive: true
    tagcloud: true
    tag: true
    category: true

# Intro widgit
intro:
  photo: img/self-photo.png ## "path/to/file" or URL
  description: |
    A user of Hexo.
  email_img_files:
    - path: img/not-easily-guessable-name.png ## "path/to/file" or URL
  links:
    - title: Homepage
      url: https://www.example.com
    - title: Contact me
      url: https://example.com/contact

# Links widget
links:
 - title: Hexo
   url: https://hexo.io
 - title: Hexo Themes
   url: https://hexo.io/themes
 - title: Wakaba - Hexo Theme
   url: https://github.com/seaoak/hexo-theme-wakaba

# Notice widget
notice:
  body_html: |
    <p>Except as otherwise noted, the content of this page is licensed under
    <a href="https://creativecommons.org/licenses/by/4.0/legalcode">the Creative Commons Attribution 4.0 License (CC BY 4.0)</a>,
    and code samples are licensed under
    <a href="https://directory.fsf.org/wiki/License:X11">the MIT License (the X11 License)</a>.
    </p>
