archives: Archives
archives_with: Archives: %s
categories: Categories
category: Category
comment: Comments
excerpt_link: Read More
home: Home
monthly_format: MMM, YYYY
newer: Newer
next: Next
older: Older
page: Page %d
powered_by: Powered by
prev: Prev
recent_posts: Recent Posts
rss_feed: RSS Feed
search: Search
share: Share
tagcloud: Tag Cloud
tags: Tags
tag: Tag
tweets: Tweets
yearly_format: YYYY
